repos:
  - repo: local
    hooks:
      - id: make format lock
        name: make format lock
        entry: bash -c "source .venv/bin/activate && make format lock"
        language: system
        always_run: true
        pass_filenames: false
        stages: [pre-commit]
      - id: make
        name: make
        entry: bash -c "source .venv/bin/activate && make --always-make --jobs"
        language: system
        always_run: true
        pass_filenames: false
        stages: [pre-push]
